// --------------------------------------------------------------------------
// -- utilities-string.js
// -- initial author: Renick Bell (renick@gmail.com)
// -- initial creation date: Wed Jun 28 10:08:48 AM CST 2023
// -- contributors: Yiler Huang (yiler7777@gmail.com); Steve Wang (stevesg168@gmail.com)
// -- license: GPL 3.0
// --------------------------------------------------------------------------

//Count how many of the same letters there are before a new one is found:
function countLetterChanges(string) {
  const counts = [];
  let currentCount = 1;
  for (let i = 1; i < string.length; i++) {
    if (string[i] !== string[i - 1]) {
      counts.push(currentCount);
      currentCount = 1;
    } else {
      currentCount++;
    }
  }
  counts.push(currentCount); // Push the count of the last letter
  return counts;
}

//Shuffles a string in a random way:
function shuffleString(str) {
  var arr = str.split('');
  var len = arr.length;
  for (var i = len - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]; // Use array destructuring for swapping
  }
  return arr.join('');
}
//generated by Chatgpt

//Loops a string by a certain amount of times:
function repeatString (times, string){
    return buildArray(times, x => {return string}).join('')
}
